#include "gpio.h"

#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/gpio.h>

void sys_gpio_init(void)
{
    // Configure the GPIO pin modes.

    // USART1: TX PB6, RX PB7
    gpio_set_mode(GPIO_BANK_USART1_RE_TX, GPIO_MODE_OUTPUT_50_MHZ, GPIO_CNF_OUTPUT_ALTFN_PUSHPULL, GPIO_USART1_RE_TX);
    gpio_set_mode(GPIO_BANK_USART1_RE_RX, GPIO_MODE_INPUT, GPIO_CNF_INPUT_PULL_UPDOWN, GPIO_USART1_RE_RX);

    // LEDs
    gpio_set_mode(GPIO_BANK_USER1_LED, GPIO_MODE_OUTPUT_2_MHZ, GPIO_CNF_OUTPUT_PUSHPULL, GPIO_USER1_LED);
    gpio_set_mode(GPIO_BANK_USER2_LED, GPIO_MODE_OUTPUT_2_MHZ, GPIO_CNF_OUTPUT_PUSHPULL, GPIO_USER2_LED);
    gpio_set_mode(GPIO_BANK_ERROR_LED, GPIO_MODE_OUTPUT_2_MHZ, GPIO_CNF_OUTPUT_PUSHPULL, GPIO_ERROR_LED);

    // Ethernet PHY MDC/MDIO
    gpio_set_mode(GPIO_BANK_RMII_MDIO, GPIO_MODE_OUTPUT_50_MHZ, GPIO_CNF_OUTPUT_ALTFN_PUSHPULL, GPIO_RMII_MDIO);
    gpio_set_mode(GPIO_BANK_RMII_MDC, GPIO_MODE_OUTPUT_50_MHZ, GPIO_CNF_OUTPUT_ALTFN_PUSHPULL, GPIO_RMII_MDC);

    // Ethernet PHY RMII
    gpio_set_mode(GPIO_BANK_RMII_REFCLK, GPIO_MODE_INPUT, GPIO_CNF_INPUT_FLOAT, GPIO_RMII_REFCLK);
    gpio_set_mode(GPIO_BANK_RMII_TX, GPIO_MODE_OUTPUT_50_MHZ, GPIO_CNF_OUTPUT_ALTFN_PUSHPULL, GPIO_RMII_TXEN | GPIO_RMII_TXD0 | GPIO_RMII_TXD1);
    gpio_set_mode(GPIO_BANK_RMII_RX, GPIO_MODE_INPUT, GPIO_CNF_INPUT_FLOAT, GPIO_RMII_RXD0 | GPIO_RMII_RXD1);
    gpio_set_mode(GPIO_BANK_RMII_CRS_DV, GPIO_MODE_INPUT, GPIO_CNF_INPUT_FLOAT, GPIO_RMII_CRS_DV);

    // Configure all alternate function remaps.
    // AFIO_MAPR_USART1_REMAP: TX PB6, RX PB7
    gpio_primary_remap(AFIO_MAPR_SWJ_CFG_JTAG_OFF_SW_ON, AFIO_MAPR_USART1_REMAP | AFIO_MAPR_MII_RMII_SEL);
}